echo "deb [arch=armhf,arm64] http://ports.ubuntu.com/ubuntu-ports/ trusty main restricted" >> /etc/apt/sources.list
echo "deb-src [arch=armhf,arm64] http://ports.ubuntu.com/ubuntu-ports/ trusty main restricted" >> /etc/apt/sources.list
echo "deb [arch=armhf,arm64] http://ports.ubuntu.com/ubuntu-ports/ trusty-updates main restricted" >> /etc/apt/sources.list
echo "deb-src [arch=armhf,arm64] http://ports.ubuntu.com/ubuntu-ports/ trusty-updates main restricted" >> /etc/apt/sources.list
echo "deb [arch=armhf,arm64] http://ports.ubuntu.com/ubuntu-ports/ trusty universe" >> /etc/apt/sources.list
echo "deb-src [arch=armhf,arm64] http://ports.ubuntu.com/ubuntu-ports/ trusty universe" >> /etc/apt/sources.list
echo "deb [arch=armhf,arm64] http://ports.ubuntu.com/ubuntu-ports/ trusty-updates universe" >> /etc/apt/sources.list
echo "deb-src [arch=armhf,arm64] http://ports.ubuntu.com/ubuntu-ports/ trusty-updates universe" >> /etc/apt/sources.list
echo "deb [arch=armhf,arm64] http://ports.ubuntu.com/ubuntu-ports/ trusty multiverse" >> /etc/apt/sources.list
echo "deb-src [arch=armhf,arm64] http://ports.ubuntu.com/ubuntu-ports/ trusty multiverse" >> /etc/apt/sources.list
echo "deb [arch=armhf,arm64] http://ports.ubuntu.com/ubuntu-ports/ trusty-updates multiverse" >> /etc/apt/sources.list
echo "deb-src [arch=armhf,arm64] http://ports.ubuntu.com/ubuntu-ports/ trusty-updates multiverse" >> /etc/apt/sources.list